version: "3"
services:
  member_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: reading-point/member_service:v1.0
    container_name: reading-point-member-app-service
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    tty: true
    environment:
      SERVICE_NAME: member_service
      SERVICE_TAGS: v1
      APP_NAME: member_service
      APP_ENV: local
      APP_KEY: 28ef3d143ba729acf55d43f3a0f12c65
      APP_DEBUG: 0
      APP_URL: http://member_service
      APP_TIMEZONE: UTC

      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL:

      DB_CONNECTION: mysql
      DB_HOST: reading-point-member-db-service
      DB_PORT: 3306
      DB_DATABASE: reading_point_member
      DB_USERNAME: root
      DB_PASSWORD: unpri2022

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: sync
      REDIS_HOST: reading-point-member-redis-service
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: halotec123

      AUTH_SERVICE_URL: http://reading-point-auth-app-service:8000

    working_dir: /var/www/html

    command: php -S member_service:8000 -t public
    ports:
      - "8903:8000"
    networks:
      - reading-point-member-network
      - reading-point-auth-service-network

  reading_point_db:
    image: mariadb:10.6
    container_name: reading-point-member-db-service
    volumes:
      - reading-point-member-service-db:/var/lib/mysql
    restart: unless-stopped
    tty: true

    environment:
      MYSQL_DATABASE: reading_point_member
      MYSQL_ROOT_PASSWORD: unpri2022
    networks:
      - reading-point-member-network
  redis_service:
    image: redis:7.0.5-alpine
    container_name: reading-point-member-redis-service
    environment:
      - REDIS_PORT_NUMBER=6379

    command: redis-server --save 20 1 --loglevel warning --requirepass halotec123
    volumes:
      - cache:/data
    networks:
      - reading-point-member-network
networks:
  reading-point-member-network:
    driver: bridge
    name: reading-point-member-network
  reading-point-auth-service-network:
    external: true
    name: reading-point-auth-network

volumes:
  reading-point-member-service-db:
    driver: local
    name: reading-point-member-service-db-vol
  cache:
    driver: local
    name: reading-point-member-redis_cache

